import type { Bottle } from '@/lib/types';

export const BOTTLES_SEED: Bottle[] = [
  {
    id: 'glenfiddich-18',
    distillerySlug: 'glenfiddich',
    name: '18 Year Old',
    fullName: 'Glenfiddich 18',
    ageYears: 18,
    abv: 40.0,
    caskType: 'Sherry',
    expression: 'Our Original Twelve, aged eighteen',
    expressionKo: '오리지널 12년의 깊이를 18년으로',
    bottleStyle: 'malt',
    msrpKrw: 200000,
    region: 'Speyside',
  },
  {
    id: 'glenfiddich-12',
    distillerySlug: 'glenfiddich',
    name: '12 Year Old',
    fullName: 'Glenfiddich 12',
    ageYears: 12,
    abv: 40.0,
    caskType: 'Bourbon/Sherry',
    bottleStyle: 'malt',
    msrpKrw: 70000,
    region: 'Speyside',
  },
  {
    id: 'macallan-12',
    distillerySlug: 'macallan',
    name: '12 Sherry Oak',
    fullName: 'The Macallan 12 Sherry Oak',
    ageYears: 12,
    abv: 40.0,
    caskType: 'Sherry',
    bottleStyle: 'malt',
    msrpKrw: 180000,
    region: 'Speyside',
  },
  {
    id: 'ardbeg-10',
    distillerySlug: 'ardbeg',
    name: '10 Year Old',
    fullName: 'Ardbeg 10',
    ageYears: 10,
    abv: 46.0,
    caskType: 'Bourbon',
    bottleStyle: 'islay',
    msrpKrw: 130000,
    region: 'Islay',
  },
  {
    id: 'ardbeg-uigeadail',
    distillerySlug: 'ardbeg',
    name: 'Uigeadail',
    fullName: 'Ardbeg Uigeadail',
    abv: 54.2,
    caskType: 'Sherry',
    bottleStyle: 'islay',
    msrpKrw: 220000,
    region: 'Islay',
  },
  {
    id: 'lagavulin-16',
    distillerySlug: 'lagavulin',
    name: '16 Year Old',
    fullName: 'Lagavulin 16',
    ageYears: 16,
    abv: 43.0,
    caskType: 'Refill',
    bottleStyle: 'islay',
    msrpKrw: 180000,
    region: 'Islay',
  },
  {
    id: 'highland-park-15',
    distillerySlug: 'highland-park',
    name: '15 Viking Heart',
    fullName: 'Highland Park 15',
    ageYears: 15,
    abv: 44.0,
    caskType: 'Sherry',
    bottleStyle: 'highland',
    msrpKrw: 200000,
    region: 'Orkney',
  },
  {
    id: 'talisker-10',
    distillerySlug: 'talisker',
    name: '10 Year Old',
    fullName: 'Talisker 10',
    ageYears: 10,
    abv: 45.8,
    caskType: 'Refill',
    bottleStyle: 'highland',
    msrpKrw: 100000,
    region: 'Highlands',
  },
  {
    id: 'yamazaki-12',
    distillerySlug: 'yamazaki',
    name: '12 Year Old',
    fullName: 'Yamazaki 12',
    ageYears: 12,
    abv: 43.0,
    caskType: 'Mizunara/Sherry',
    bottleStyle: 'japan',
    msrpKrw: 350000,
    region: 'Japan',
  },
  {
    id: 'hibiki-harmony',
    distillerySlug: 'hibiki',
    name: 'Japanese Harmony',
    fullName: 'Hibiki Japanese Harmony',
    abv: 43.0,
    caskType: 'Mizunara/Sherry/Bourbon',
    bottleStyle: 'japan',
    msrpKrw: 200000,
    region: 'Japan',
  },
  {
    id: 'makers-mark',
    distillerySlug: 'makers-mark',
    name: 'Original',
    fullName: "Maker's Mark",
    abv: 45.0,
    caskType: 'New Oak',
    bottleStyle: 'bourbon',
    msrpKrw: 65000,
    region: 'Kentucky',
  },
  {
    id: 'buffalo-trace',
    distillerySlug: 'buffalo-trace',
    name: 'Bourbon',
    fullName: 'Buffalo Trace',
    abv: 45.0,
    caskType: 'New Oak',
    bottleStyle: 'bourbon',
    msrpKrw: 75000,
    region: 'Kentucky',
  },
];

export const REGIONS = [
  'Speyside', 'Islay', 'Highlands', 'Lowlands', 'Campbeltown',
  'Japan', 'Kentucky', 'Tennessee', 'Ireland', 'Taiwan', 'India', 'Orkney',
] as const;

export const CASK_TYPES = [
  'Bourbon', 'Sherry', 'Refill', 'Port', 'Rum', 'Virgin Oak',
  'Mizunara', 'Madeira', 'Sauternes', 'Wine', 'New Oak',
] as const;
